macro (_format_string str length return)
    string (LENGTH "${str}" _str_len)
    math (EXPR _add_chr "${length} - ${_str_len}")
    set (${return} "${str}")
    while (_add_chr GREATER 0)
	set (${return} "${${return}} ")
	math (EXPR _add_chr "${_add_chr} - 1")
    endwhile (_add_chr GREATER 0)
endmacro (_format_string str length return)

macro (_print_result_message _name _var)
    _format_string ("${_name}" 30 __name)
    if (${_var})
	set (_result "Yes")
    else (${_var})
	set (_result "No")
    endif (${_var})
    message ("   ${__name} : ${_result}")
endmacro (_print_result_message)

macro (_print_configure_header)
    _format_string ("${PROJECT_NAME}" 40 _project)
    _format_string ("${VERSION}" 40 _version)
    message ("\n************************************************************")
    message ("* Compiz Buildsystem                                       *")
    message ("*                                                          *")
    message ("* Version : ${_version}       *")
    message ("************************************************************")
endmacro (_print_configure_header)

macro (_print_configure_footer)
    message ("************************************************************")
endmacro (_print_configure_footer)


macro (_print_configure_results)
    _print_configure_header ()
#    message ("\n Optional plugins:")
    message ("\n Optional features:")
    _print_result_message ("gtk window decorator" USE_GTK)
    _print_result_message ("metacity theme support" USE_METACITY)
    _print_result_message ("gconf schemas" USE_GCONF)
    _print_result_message ("gnome" USE_GNOME)
    _print_result_message ("kde4 window decorator" USE_KDE4)

    _print_configure_footer ()
endmacro (_print_configure_results)
